config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # make /signup as the standard url to go to the users#new page
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  get "/search", to: "jobs#search"
  
  # disable users from accessing index and about if they are not logged in
  resources :users, except: [:index, :about]
  resources :sessions, except: [:index, :edit, :edit, :show, :new, :destroy]
  resources :jobs do
    resources :reviews
  end
  resources :passwords
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about"
  # Defines the root path route ("/")
  root "sites#index"
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :job_title, presence:true
    validates :location, presence:true
    validates :category, presence:true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate
  
  # HTTP method: GET
  # URL: /jobs
  def index
    @jobs = Job.all
  end
  
  # HTTP method: GET
  # URL: /jobs/new
  def new
    @job = Job.new
  end
  
  # HTTP method: POST
  # URL: /jobs
  def create
    @job = Job.new job_params
    if @job.save
      redirect_to jobs_path, notice: "Job added."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  # HTTP method: GET
  # URL: /jobs/:id
  def show 
    load_job
  end
  
  # HTTP method: GET
  # URL: /jobs/:id/edit
  def edit
    load_job
  end
  
  # HTTP method: PATCH/PUT
  # URL: /jobs/:id
  def update
    load_job
    if @job.update job_params
      redirect_to @job, notice: "Job was updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  # HTTP method: DELETE
  # URL: /jobs/:id
  def destroy
    load_job
    @job.destroy
    redirect_to jobs_path, alert: "Job was deleted."
  end
  
  def search
    if params[:search].blank?
      redirect_to jobs_path
    else
      @parameter = params[:search].downcase
      @results = Job.all.where("lower(job_title) LIKE :search", search: "%#{@parameter}%")
      @count = @results.count
    end
  end
  
  private
  def load_job
    @job = Job.find params[:id]
  end
  
  def job_params
    params.require(:job).permit(:job_title, :location, :category)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="text-center col-md-7 col-lg-8 mx-auto">
    <div class="row g-3">
      <div class="col">
        <%= bootstrap_form_with(model: @job) do |f| %>
          <%= f.alert_message "Please fix the errors below.", error_summary: false %>
          <%= f.text_field :job_title %>
          <%= f.text_area :location %>
          <%= f.text_field :category %>
          <%= f.primary @job.persisted? ? 'Update Job' : 'Add Job' %>
        <% end %>
      </div>
  </div>

app/views/jobs/_job.html.erb
<div class="col">
  <div class="card">
    <div class="card-body job" id="<%= dom_id(job) %>">
      <h5 class="card-title"><%= link_to_unless_current job.job_title, job %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= job.location %></h6>
      <p class="card-subtitle mb-2 text-muted"><%= job.category %></p>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<div class="pricing-header px-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Edit Job</h1>
    <div class="justify-content-center mx-auto pb-md-4">
      <%= render 'form' %>
    </div>
</div>

app/views/jobs/index.html.erb
<div class="px-4 container-fluid">
    <div class="pricing-header px-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Jobs</h1>
    <p>
        <%= link_to "New Job", new_job_path, class: "btn btn-primary" %>
    </p>
    </div>
    
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-5">
        <% @jobs.each do |job| %>
        <%= render job %>
        <% end %>
    </div>
</div>

app/views/jobs/new.html.erb
<div class="pricing-header px-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Add Job</h1>
    <div class="justify-content-center mx-auto pb-md-4">
      <%= render 'form' %>
    </div>
</div>

app/views/jobs/search.html.erb
<h3> Search Results (<%= @count %>)</h3>
<% @results.each do |result| %>
    <%= render result %>
<% end %>

app/views/jobs/show.html.erb
<div class="px-4 container-fluid">
    <div class="pricing-header px-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4">View Job</h1>
    <div class="px-4 py-4 mx-auto">
        <%= render @job %>
    </div>
    <p>
        <%= link_to "Edit Job", edit_job_path(@job) %> | <%= link_to "All Jobs", jobs_path %> | <%= link_to "Reviews about this job", job_reviews_path(@job) %>
        <%= button_to "Delete Job", @task, method: :delete, class: 'btn btn-secondary', form: {
                data: {
                    turbo_confirm: "Are you sure you want to delete this job?"
                }
            }
        %>
    </p>
    </div>
</div>