config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # make /signup as the standard url to go to the users#new page
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  get "/search", to: "jobs#search"
  
  # disable users from accessing index and about if they are not logged in
  resources :users, except: [:index, :about]
  resources :sessions, except: [:index, :edit, :edit, :show, :new, :destroy]
  resources :jobs do
    resources :reviews
  end
  resources :passwords
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about"
  # Defines the root path route ("/")
  root "sites#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate
  before_action :load_job
  before_action :load_review, except: [:index, :new, :create]
 
 def index
  @reviews = current_user.reviews.all
 end 

 def new
  @review = Review.new
 end
 
 def create
  @review = Review.new review_params
  @review.user = current_user
  @review.job = @job
  if @job.reviews << @review
   redirect_to job_review_path(@job,@review), notice: "Review added successfully."
  else
   render :new, status: :unprocessable_entity
  end
 end
 
 def show
 end
 
 def edit
 end
 
 def update
  if @review.update review_params
      redirect_to job_review_path(@job,@review), notice: "Review has been updated."
  else
      render :edit, status: :unprocessable_entity
  end
 end
 
 def destroy
   @review.destroy
   redirect_to job_reviews_path(@job), alert: "Review has been deleted."
 end
 
 private
 
 def review_params 
  params.require(:review).permit(:hiring_manager_name, :pros, :cons, :work_hours, :anonymous)
 end
 
 def load_job
  @job = Job.find params[:job_id]
 end
 
 def load_review
  @review = @job.reviews.find params[:id]
 end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= bootstrap_form_with(model: [@job,@review]) do |f| %>
  <%= f.alert_message "Please fix the errors below.", error_summary: false %>
  <%= f.text_field :work_hours %>
  <%= f.text_area :pros %>
  <%= f.text_area :cons %>
  <%= f.text_field :hiring_manager_name %>
  <%= f.check_box :anonymous %>
  <%= f.primary @review.persisted? ? 'Update Review' : 'Submit Review' %>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id(review) %>" class="review">
  <p><%= link_to_unless_current review.pros, job_review_path(@job,review) %></p>
  <p><strong>Work Hours: </strong><%= review.work_hours %></p>
  <p><strong>Pros: </strong><%= review.pros %></p>
  <p><strong>Cons: </strong><%= review.cons %></p>
  <p><strong>Hiring Manager Name: </strong><%= review.hiring_manager_name %></p>
</div>

app/views/reviews/edit.html.erb
<% title "Edit Review" %>

<%= render 'form' %>

app/views/reviews/index.html.erb
<% title "Reviews for "+@job.job_title %>

<%= render @job.reviews %>

<%= link_to "Add Review", new_job_review_path(@job), class: "btn btn-primary" %>
<br>
<%= link_to "Back to Job", job_path(@job) %>

app/views/reviews/new.html.erb
<% title "New Review" %>

<%= render 'form' %>

app/views/reviews/show.html.erb
<% title "Review for "+@job.job_title %>

<%= render @review %>

<% if @review.user == current_user %>
    <%= link_to "Edit Review", edit_job_review_path(@job,@review) %> |
<% end %>

<%= link_to "All Reviews", job_reviews_path(@job) %>

<% if @review.user == @current_user %>
    <%= button_to "Delete Review", [@job,@review], method: :delete, class: 'btn btn-secondary', form: {
            data: {
                turbo_confirm: "Are you sure you want to delete this job?"
            }
        }
    %>
<% end %>
<br>