config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # make /signup as the standard url to go to the users#new page
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  get "/search", to: "jobs#search"
  
  # disable users from accessing index and about if they are not logged in
  resources :users, except: [:index, :about]
  resources :sessions, except: [:index, :edit, :edit, :show, :new, :destroy]
  resources :jobs do
    resources :reviews
  end
  resources :passwords
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about"
  # Defines the root path route ("/")
  root "sites#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyJob<%= " | "+yield(:title) unless yield(:title).blank? %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <!-- Navbar -->
    <header class="p-3 mb-3">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <%= link_to "RateMyJob", root_path, class: "navbar-brand fw-bold"%>
  
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <%= nav_link 'Home', root_path %>
            <%= nav_link 'Jobs', jobs_path %>
            <%= nav_link 'About', about_path %>
          </ul>
  
          <ul class="nav mb-md-0">
            <% if current_user %>
              <%= nav_link current_user.name, user_path(current_user) %>
              <%= nav_link 'Log out', logout_path %>
            <% else %>
              <%= nav_link 'Login', login_path %>
              <%= nav_link 'Sign Up', signup_path %>
            <% end %>
            <%= form_tag(search_path, :method => "get") do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], placeholder: "Type a job ...", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "Search", :class => 'btn btn-icon glyphican glyphicon-search', :name => nil %>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
  
    <!-- End Navbar -->
    <main class="container-fluid">
      <!-- Flash message -->
      <div id="flash-messages" class="w-75">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == 'notice' ? 'primary' : 'danger' %> alert-dismissable fade show d-flex justify-content-between" role="alert">
          <p>
            <strong><%= msg %></strong>
          </p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </div>
      <!-- End Flash message -->
      <div class="px-4 my-5">
        <% if @show_title %>
        <div id="title" class="row">
          <div class="col">
            <h1><%= yield(:title) %></h1>
          </div>
        </div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <span class="text-muted">&copy; Sheryl Tania, 2022.</span>
      </div>
    </footer>
  </body>
</html>